### ISSUE TITLE
看完readme从哪里开始学呢？

### ISSUE THREAD

**Issue by psy358** [windsting/little-aspnetcore-book#4]

**Comment by windsting** [comment]
repository 的 description 里有个链接：
https://windsting.github.io/little-aspnetcore-book/book/

但是这本书现在已经outdated了，
asp.net core 连 5.0 和 7.0 都 Out of support 了，
更不用说书里的 2.0 了。

**Comment by windsting** [comment]
repository 的 description 里有个链接：
https://windsting.github.io/little-aspnetcore-book/book/

但是这本书现在已经outdated了，
asp.net core 连 5.0 和 7.0 都 Out of support 了，
更不用说书里的 2.0 了。
